// File generated by FlutterFire CLI.
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp7gBJ_5YTxHS2iDG00Eqh5LKAy3fRuCE',
    appId: '1:148926643297:web:8e2112017c7041a8d0fe20',
    messagingSenderId: '148926643297',
    projectId: 'gestion-salles-unz',
    authDomain: 'gestion-salles-unz.firebaseapp.com',
    storageBucket: 'gestion-salles-unz.firebasestorage.app',
    measurementId: 'G-1RL0L1DFMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzIJfC5nIfiDFMA9q-wwUB1T4hp4cln4k',
    appId: '1:148926643297:android:4af8516edb2c5f4dd0fe20',
    messagingSenderId: '148926643297',
    projectId: 'gestion-salles-unz',
    storageBucket: 'gestion-salles-unz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHsE5yZK0MPSBj3gWOjtJgYiO1N9ziZ8k',
    appId: '1:148926643297:ios:79d0f9c574b45e97d0fe20',
    messagingSenderId: '148926643297',
    projectId: 'gestion-salles-unz',
    storageBucket: 'gestion-salles-unz.firebasestorage.app',
    iosBundleId: 'com.example.gestionSalles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHsE5yZK0MPSBj3gWOjtJgYiO1N9ziZ8k',
    appId: '1:148926643297:ios:79d0f9c574b45e97d0fe20',
    messagingSenderId: '148926643297',
    projectId: 'gestion-salles-unz',
    storageBucket: 'gestion-salles-unz.firebasestorage.app',
    iosBundleId: 'com.example.gestionSalles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp7gBJ_5YTxHS2iDG00Eqh5LKAy3fRuCE',
    appId: '1:148926643297:web:f12ea9037c90b8ead0fe20',
    messagingSenderId: '148926643297',
    projectId: 'gestion-salles-unz',
    authDomain: 'gestion-salles-unz.firebaseapp.com',
    storageBucket: 'gestion-salles-unz.firebasestorage.app',
    measurementId: 'G-5DQRGKLHSH',
  );
}
